services:
  homeassistant:
    container_name: homeassistant
    image: registry.cn-hangzhou.aliyuncs.com/hasscc/hacn:stable
    restart: unless-stopped
    networks:
      docker:
        mac_address: 02:42:ac:22:00:03
    volumes:
      - /mnt/nas/pve/volumes/homeassistant:/config
      # File pre-positioned in the PVE path; avoiding bind mounts to ensure availability
      # even if the source directory is unmounted.
      # - ./configuration.yaml:/config/configuration.yaml:ro
    environment:
      TZ: Asia/Shanghai

networks:
  docker:
    external: true
