version: "3"

tasks:
  open:
    desc: Open Home Assistant homepage in browser
    vars:
      URL: http://homeassistant.docker:8123
    cmds:
      - cmd: cmd /c start "" "{{.URL}}"
        platforms: [windows]
      - cmd: open "{{.URL}}"
        platforms: [darwin]
      - cmd: xdg-open "{{.URL}}"
        platforms: [linux]
