version: "3"

tasks:
  open:
    desc: Open Home Assistant homepage in browser
    vars:
      URL: http://homeassistant.docker:8123
    cmds:
      - cmd: cmd /c start "" "{{.URL}}"
        platforms: [windows]
      - cmd: open "{{.URL}}"
        platforms: [darwin]
      - cmd: xdg-open "{{.URL}}"
        platforms: [linux]

  push:
    desc: Upload the Home Assistant configuration
    cmds:
      - scp configuration.yaml docker:/opt/data/homeassistant/configuration.yaml
