services:
  alloy:
    image: grafana/alloy
    container_name: alloy
    restart: unless-stopped
    labels:
      service_repository: https://github.com/grafana/alloy
    privileged: true
    pid: host
    networks:
      - docker
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - alloy_config:/etc/alloy
      - alloy_data:/var/lib/alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    tmpfs:
      - /tmp/symb-cache

networks:
  docker:
    external: true

volumes:
  alloy_config:
  alloy_data:
    # Pre-create via `docker volume create`
    external: true
