services:
  cadvisor:
    image: ghcr.nju.edu.cn/google/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/kmsg
    command:
      - --port=80
      - --docker_only=true
      # options are advtcp,app,cpu,cpuLoad,cpu_topology,cpuset,disk,diskIO,hugetlb,memory,memory_numa,network,oom_event,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp
      - --enable_metrics=cpu,memory,network,diskIO
      - --housekeeping_interval=20s
      - --store_container_labels=false
    privileged: true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
    healthcheck: 
      disable: true

networks:
  docker:
    external: true
