version: "3"

tasks:
  open:
    desc: Open cAdvisor homepage in browser
    vars:
      URL: http://cadvisor.docker
    cmds:
      - cmd: cmd /c start "" "{{.URL}}"
        platforms: [windows]
      - cmd: open "{{.URL}}"
        platforms: [darwin]
      - cmd: xdg-open "{{.URL}}"
        platforms: [linux]
