# assign static IPv4 addresses to specific PVE VMs
# make sure static route rule is setup
dhcp-host=BC:24:11:F4:87:EF,192.168.9.100,docker

# forward subnet dns request
server=/docker/192.168.9.53

# also add subnet domain to dns suffix list
# https://stackoverflow.com/questions/22775531/cant-get-dnsmasq-to-push-multiple-search-prefixes
dhcp-option=option:domain-search,lan.kokomi.site,docker
