services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - type: volume
        source: prometheus_data
        target: /prometheus
        volume:
          subpath: data
      - type: volume
        source: prometheus_data
        target: /etc/prometheus
        volume:
          subpath: config
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      # for query.log and fail.log
      - /run/log
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.config.file=/etc/prometheus/web.yml
      - --web.listen-address=:443

networks:
  docker:
    external: true

volumes:
  prometheus_data:
    # Pre-create via `docker volume create`
    external: true
