services:
  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - pyroscope_data:/var/lib/pyroscope
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

networks:
  docker:
    external: true

volumes:
  pyroscope_data:
    # Pre-create via `docker volume create`
    external: true
