services:
  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - pyroscope_data:/var/lib/pyroscope
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      # 尝试降低 CPU 占用
      GOGC: 300
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID must be set in .env}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET must be set in .env}
      GITHUB_SESSION_SECRET: ${GITHUB_SESSION_SECRET:?GITHUB_SESSION_SECRET must be set in .env}
    command: 
      - -self-profiling.disable-push=true

networks:
  docker:
    external: true

volumes:
  pyroscope_data:
    # Pre-create via `docker volume create`
    external: true
