services:
  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    restart: unless-stopped
    networks:
      - docker
    depends_on:
      certs:
        condition: service_completed_successfully
    volumes:
      - pyroscope_data:/var/lib/pyroscope\
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

networks:
  docker:
    external: true

volumes:
  pyroscope_data:
    # Pre-create via `docker volume create`
    external: true
