services:
  coredns:
    # Seed local files into a volume to decouple from the CIFS mount,
    # ensuring availability even if the remote share goes offline.
    container_name: coredns
    build:
      context: .
      dockerfile_inline: |
        FROM coredns/coredns:latest
        COPY ./Corefile /app/Corefile
    restart: always
    labels:
      service_repository: https://github.com/coredns/coredns
    dns:
      # Avoid 127.0.0.11 re-resolving docker internal domains, which would cause a loop
      - 223.5.5.5
    networks:
      docker:
        ipv4_address: 192.168.9.53
    command: -conf /app/Corefile
    environment:
      TZ: Asia/Shanghai

networks:
  docker:
    # To create the macvlan network, run the following command:
    # docker network create -d macvlan --ipv6 \
    #   -o parent=ens18 \
    #   --subnet=192.168.9.0/24 --gateway=192.168.9.1 --ip-range=192.168.9.224/27 \
    #   docker
    external: true
