version: '3'

tasks:
  recreate:*:
    vars:
      SERVICE: '{{index .MATCH 0}}'
    dir: '{{.SERVICE}}'
    cmds:
      - docker compose up --detach --build

  upgrade:*:
    vars:
      SERVICE: '{{index .MATCH 0}}'
    dir: '{{.SERVICE}}'
    cmds:
      - docker compose pull
      - docker compose up --detach --build

  new_cert:
    summary: |
      Generate new certificate with certbot.
      task new_cert -- domain_a,domain_b
    cmds:
      - certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/private/certbot/cloudflare.ini -d {{.CLI_ARGS}}
