services:
  influxdb-explorer:
    container_name: influxdb-explorer
    image: influxdata/influxdb3-ui:latest
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - db:/db
    environment:
      TZ: Asia/Shanghai
    command: ["--mode=admin"]

networks:
  docker:
    external: true

volumes:
  db:
