version: "3"

tasks:
  deploy-rt-ax86u:
    desc: Deploy files to RT-AX86U Router
    cmds:
      - scp -rpO jffs koolshare RT-AX86U-CE58:/
      - ssh RT-AX86U-CE58 "sh /koolshare/init.d/N200enihsyou.sh start_nat"

  deploy-tftpboot:
    desc: Deploy tftpboot files on remote
    cmds:
      - git clone https://github.com/enihsyou/netboot.xyz.git --depth=1
      - defer: rm -rf netboot.xyz
      - cd netboot.xyz
      - defer: cd ..
      - docker build -t localbuild -f Dockerfile . 
      - docker run -it -v "$(pwd):/buildout" localbuild
      - rsync -avzh -CP ./buildout/ enihsyou.synology.me:/volume2/pve/tftproot/netboot.xyz/
