services:
  apprise:
    container_name: apprise
    image: caronc/apprise:latest
    restart: unless-stopped
    networks:
      - docker
    volumes:
      - /opt/data/apprise/config:/config
      - /opt/data/apprise/attach:/attach
      - /etc/localtime:/etc/localtime:ro
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: 1
      APPRISE_ADMIN: "y"

networks:
  docker:
    external: true
