# After starting the container, make sure to reroute server name like
# 'deb.debian.org' to the container in local DNS server.
services:
  alpine-redirect:
    container_name: cdnmirror
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:alpine
        COPY ./templates /etc/nginx/templates
    restart: unless-stopped
    networks:
      docker:
        ipv4_address: 192.168.2.99
    logging:
      options:
        max-size: "1m"

networks:
  docker:
    external: true
