# After starting the container, make sure to reroute server name like
# 'deb.debian.org' to the container in local DNS server.
services:
  main:
    container_name: cdnmirror
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:alpine
        COPY ./templates /etc/nginx/templates
    restart: unless-stopped
    networks:
      docker:
        # The host file on the router resolves some domains to the IP where caddy is located
        ipv4_address: 192.168.9.99
    logging:
      options:
        # access log is written to /var/log/nginx/access.log which is symlinked to /dev/stdout,
        # so we can view the log with `docker logs`. this is done by Dockerfile-alpine-slim
        max-size: "1m"

networks:
  docker:
    external: true
