##################### Grafana Customized Configuration #####################
# Everything in this file will override the default grafana.ini configuration file.
# Only changed values with or without documentation will be included in this file.
# Visit https://github.com/grafana/grafana/blob/main/conf/sample.ini to see all options.

[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false

[news]
news_feed_enabled = false

[auth.anonymous]
enabled = true

[plugins]
preinstall_auto_update = false

[profiling]
enabled = true

[metrics]
enabled = true
disable_total_stats = false
classic_http_histogram_enabled = false

[feature_toggles]
enable = provisioning.userAttribution

[server]
# 内网环境，降低 CPU 消耗
enable_gzip = false

[database]
# 我们是单实例
high_availability = false

[dashboard_cleanup]
# 你完全不通过 /apis 删除 dashboard，没必要每 30 秒扫描
interval = 168h
batch_size = 5
