##################### Grafana Customized Configuration #####################
# Everything in this file will override the default grafana.ini configuration file.
# Only changed values with or without documentation will be included in this file.
# Visit https://github.com/grafana/grafana/blob/main/conf/sample.ini to see all options.

[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false

[news]
news_feed_enabled = false
