services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - docker
    environment:
      GF_SERVER_HTTP_PORT: 80
      GF_AUTH_ANONYMOUS_ENABLED: true
    volumes:
      - grafana_data:/var/lib/grafana
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

networks:
  docker:
    external: true

volumes:
  grafana_data:
    # Pre-create via `docker volume create`
    external: true
