services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    labels:
      pyroscope.pprof_port: "6060"
    networks:
      - docker
    environment:
      # 尝试降低 CPU 占用
      GOGC: 300
      GF_DIAGNOSTICS_PROFILING_ENABLED: true
      GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
      GF_DIAGNOSTICS_PROFILING_BLOCK_RATE: 0
      GF_SERVER_ROOT_URL: https://grafana.home.kokomi.site
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

networks:
  docker:
    external: true

volumes:
  grafana_data:
    # Pre-create via `docker volume create`
    external: true
