services:
  umami:
    image: docker.umami.is/umami-software/umami:mysql-latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:3000
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      REDIS_URL: redis://redis:6379
      APP_SECRET: ${APP_SECRET}
    extra_hosts:
      # If connect to MySQL on the Docker host, set MYSQL_HOST to 'mysql'
      mysql: host-gateway
    depends_on:
      - redis
    networks:
      - umami_net
    init: true
    healthcheck:
      test: ["CMD", "curl -f http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
  redis:
    image: redis:7-alpine
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256MB
    networks:
      # Enabling access redis server from Linux Docker host via
      # redis-cli -h $(docker container inspect umami-redis-1 -f '{{.NetworkSettings.Networks.umami_umami_net.IPAddress}}')
      - umami_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  umami_net:
